# -*- mode: python ; coding: utf-8 -*-

import os

block_cipher = None

datas = []
if os.path.exists('config.json'):
    datas.append(('config.json', '.'))
if os.path.exists('mobile'):
    datas.append(('mobile', 'mobile'))

hidden_imports = [
    'PySide6',
    'PySide6.QtCore',
    'PySide6.QtGui',
    'PySide6.QtWidgets',
    'faster_whisper',
    'openai',
    'requests',
    'psutil',
    'pyaudio',
    'speech_recognition',
    'edge_tts',
    'pygame',
    'pyautogui',
    'selenium',
    'bs4',
    'cv2',
    'sqlite3',
    'qrcode',
    'PIL',
    'ai',
    'ai.provider',
    'ai.gemini_provider',
    'ai.openai_provider',
    'ai.local_provider',
    'core',
    'core.agent',
    'core.planner',
    'core.executor',
    'core.permissions',
    'core.verifier',
    'core.replanner',
    'core.router',
    'core.context',
    'core.tools_registry',
    'core.mobile_bridge',
    'memory',
    'memory.database',
    'memory.conversation',
    'memory.user_memory',
    'memory.retrieval',
    'tools',
    'tools.computer',
    'tools.browser',
    'tools.web',
    'tools.files',
    'tools.system',
    'tools.applications',
    'tools.office',
    'tools.web_builder',
    'tools.computer_settings',
    'tools.file_processor',
    'tools.media_controller',
    'tools.productivity',
    'tools.social',
    'tools.fitness',
    'tools.smart_home',
    'tools.dev_tools',
    'tools.pairing_manager',
    'ui',
    'ui.overlay',
    'ui.system_monitor',
    'vision',
    'vision.screen',
    'vision.gestures',
    'vision.camera',
    'voice',
    'voice.speech_to_text',
    'voice.text_to_speech',
    'voice.wake_word',
    'voice.clap_detection',
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tensorflow'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='JARVIS',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
