"""
JARVIS V3.0 - Office Document Generation Tools
Native document generation for PowerPoint presentations, Excel spreadsheets,
Word documents, and PDFs.
"""

from __future__ import annotations

import os
import re
import csv
import json
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional, Union

logger = logging.getLogger("JARVIS.Tools.Office")

DEFAULT_OUTPUT_DIR = Path.home() / "Desktop" / "JARVIS" / "Documents"

def _resolve_output_path(output_path: Optional[str], default_filename: str, ext: str) -> Path:
    """Safely resolves and sanitizes output destination file path."""
    if output_path:
        path = Path(output_path).expanduser()
        if not path.is_absolute():
            head = path.parts[0].lower() if path.parts else ""
            tail = Path(*path.parts[1:]) if len(path.parts) > 1 else Path(path.name)
            if head in {"downloads", "download"}:
                path = Path.home() / "Downloads" / tail
            elif head == "desktop":
                path = Path.home() / "Desktop" / tail
            else:
                path = DEFAULT_OUTPUT_DIR / path
        if path.suffix.lower() != ext:
            path = path.with_suffix(ext)
    else:
        DEFAULT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        safe_name = re.sub(r"[^a-zA-Z0-9_-]+", "_", default_filename.strip()).strip("_") or "document"
        path = DEFAULT_OUTPUT_DIR / f"{safe_name}{ext}"

    path.parent.mkdir(parents=True, exist_ok=True)
    return path

def create_presentation(
    title: str,
    slides: Union[List[Dict[str, Any]], str],
    output_path: Optional[str] = None
) -> str:
    """
    Creates a PowerPoint (.pptx) presentation with custom styled slides.
    Args:
        title: Title of the presentation
        slides: List of dicts with 'title' and 'content'/'bullets' keys, or JSON string.
        output_path: Optional destination path.
    """
    try:
        if isinstance(slides, str):
            try:
                slides = json.loads(slides)
            except Exception:
                lines = [l.strip() for l in slides.split("\n") if l.strip()]
                slides = [{"title": f"Slide {i+1}", "bullets": [line]} for i, line in enumerate(lines)]

        dest = _resolve_output_path(output_path, title, ".pptx")

        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt
            from pptx.dml.color import RGBColor

            prs = Presentation()
            prs.slide_width = Inches(13.333)  # 16:9 widescreen
            prs.slide_height = Inches(7.5)

            # Title Slide
            title_layout = prs.slide_layouts[0]
            slide0 = prs.slides.add_slide(title_layout)
            title_shape = slide0.shapes.title
            subtitle_shape = slide0.placeholders[1]
            title_shape.text = title
            subtitle_shape.text = "Generated by JARVIS AI Assistant"

            # Content Slides
            bullet_layout = prs.slide_layouts[1]
            for s_data in slides:
                s = prs.slides.add_slide(bullet_layout)
                s_title = s_data.get("title", "Overview")
                s.shapes.title.text = s_title

                body_shape = s.placeholders[1]
                tf = body_shape.text_frame
                tf.word_wrap = True

                bullets = s_data.get("bullets") or s_data.get("content") or []
                if isinstance(bullets, str):
                    bullets = [bullets]

                for i, b_text in enumerate(bullets):
                    if i == 0:
                        p = tf.paragraphs[0]
                    else:
                        p = tf.add_paragraph()
                    p.text = str(b_text)
                    p.font.size = Pt(18)

            prs.save(str(dest))
            logger.info(f"[Office] Created presentation at {dest}")
            return f"Presentation successfully generated at: {dest}"

        except ImportError:
            dest_md = dest.with_suffix(".md")
            with open(dest_md, "w", encoding="utf-8") as f:
                f.write(f"# {title}\n\n*Generated by JARVIS AI*\n\n---\n\n")
                for s_data in slides:
                    f.write(f"## {s_data.get('title', 'Slide')}\n\n")
                    bullets = s_data.get("bullets") or s_data.get("content") or []
                    if isinstance(bullets, str):
                        bullets = [bullets]
                    for b in bullets:
                        f.write(f"- {b}\n")
                    f.write("\n---\n\n")
            return f"PowerPoint module not installed. Saved presentation as Markdown at: {dest_md}"

    except Exception as e:
        logger.error(f"[Office PPT Error]: {e}")
        return f"Failed to generate presentation: {e}"

def create_spreadsheet(
    title: str,
    sheets_data: Union[Dict[str, List[List[Any]]], List[List[Any]], str],
    output_path: Optional[str] = None
) -> str:
    """
    Creates an Excel (.xlsx) spreadsheet or CSV workbook.
    Args:
        title: Title/base filename of the workbook
        sheets_data: Dict of {sheet_name: 2D_list_of_rows} or 2D list of rows, or JSON string.
        output_path: Optional destination path.
    """
    try:
        if isinstance(sheets_data, str):
            try:
                sheets_data = json.loads(sheets_data)
            except Exception:
                rows = [line.split(",") for line in sheets_data.strip().split("\n")]
                sheets_data = {"Sheet1": rows}

        if isinstance(sheets_data, list):
            sheets_data = {"Data": sheets_data}

        dest = _resolve_output_path(output_path, title, ".xlsx")

        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment

            wb = openpyxl.Workbook()
            wb.remove(wb.active)

            header_fill = PatternFill(start_color="1F497D", end_color="1F497D", fill_type="solid")
            header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")

            for sheet_name, rows in sheets_data.items():
                ws = wb.create_sheet(title=str(sheet_name)[:31])
                for r_idx, row in enumerate(rows, start=1):
                    for c_idx, val in enumerate(row, start=1):
                        cell = ws.cell(row=r_idx, column=c_idx, value=val)
                        if r_idx == 1:
                            cell.fill = header_fill
                            cell.font = header_font
                            cell.alignment = Alignment(horizontal="center", vertical="center")

                for col in ws.columns:
                    max_len = max(len(str(cell.value or '')) for cell in col)
                    col_letter = openpyxl.utils.get_column_letter(col[0].column)
                    ws.column_dimensions[col_letter].width = max(max_len + 3, 12)

            wb.save(str(dest))
            logger.info(f"[Office] Created spreadsheet at {dest}")
            return f"Spreadsheet successfully generated at: {dest}"

        except ImportError:
            dest_csv = dest.with_suffix(".csv")
            with open(dest_csv, "w", newline="", encoding="utf-8") as f:
                writer = csv.writer(f)
                first_sheet = next(iter(sheets_data.values())) if sheets_data else []
                for row in first_sheet:
                    writer.writerow(row)
            return f"Excel module not installed. Saved spreadsheet as CSV at: {dest_csv}"

    except Exception as e:
        logger.error(f"[Office Sheet Error]: {e}")
        return f"Failed to generate spreadsheet: {e}"

def create_word_document(
    title: str,
    content: Union[List[Dict[str, str]], str],
    output_path: Optional[str] = None
) -> str:
    """
    Creates a formatted Word (.docx) document.
    Args:
        title: Document title
        content: List of dicts with 'heading' and 'text' keys, or raw string.
        output_path: Optional destination path.
    """
    try:
        dest = _resolve_output_path(output_path, title, ".docx")

        if isinstance(content, str):
            try:
                content = json.loads(content)
            except Exception:
                content = [{"heading": "Document Content", "text": content}]

        try:
            import docx
            from docx.shared import Pt, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH

            doc = docx.Document()

            t_para = doc.add_paragraph()
            t_run = t_para.add_run(title)
            t_run.font.size = Pt(24)
            t_run.font.bold = True
            t_run.font.color.rgb = RGBColor(31, 73, 125)
            t_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

            sub_p = doc.add_paragraph()
            sub_p.add_run("Generated by JARVIS Autonomous Assistant").italic = True
            sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            doc.add_paragraph()

            for item in content:
                heading = item.get("heading", "")
                text = item.get("text", "") or item.get("content", "")

                if heading:
                    h = doc.add_heading(heading, level=1)
                    if h.runs:
                        h.runs[0].font.color.rgb = RGBColor(31, 73, 125)

                if text:
                    p = doc.add_paragraph(text)
                    p.paragraph_format.line_spacing = 1.2
                    p.paragraph_format.space_after = Pt(10)

            doc.save(str(dest))
            logger.info(f"[Office] Created Word document at {dest}")
            return f"Word document successfully generated at: {dest}"

        except ImportError:
            dest_txt = dest.with_suffix(".txt")
            with open(dest_txt, "w", encoding="utf-8") as f:
                f.write(f"=== {title} ===\n\nGenerated by JARVIS\n\n")
                for item in content:
                    f.write(f"## {item.get('heading', '')}\n")
                    f.write(f"{item.get('text', '')}\n\n")
            return f"Word module not installed. Saved document as text file at: {dest_txt}"

    except Exception as e:
        logger.error(f"[Office Word Error]: {e}")
        return f"Failed to generate Word document: {e}"

def create_pdf_document(
    title: str,
    content: Union[List[Dict[str, str]], str],
    output_path: Optional[str] = None
) -> str:
    """
    Creates a formatted PDF (.pdf) document.
    Args:
        title: Document title
        content: List of dicts with 'heading' and 'text', or raw string.
        output_path: Optional destination path.
    """
    try:
        dest = _resolve_output_path(output_path, title, ".pdf")

        if isinstance(content, str):
            try:
                content = json.loads(content)
            except Exception:
                content = [{"heading": "Report", "text": content}]

        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib import colors

            doc = SimpleDocTemplate(
                str(dest),
                pagesize=letter,
                rightMargin=54,
                leftMargin=54,
                topMargin=54,
                bottomMargin=54
            )
            styles = getSampleStyleSheet()

            title_style = ParagraphStyle(
                'JarvisDocTitle',
                parent=styles['Heading1'],
                fontSize=22,
                leading=26,
                textColor=colors.HexColor('#1F497D'),
                alignment=1,
                spaceAfter=15
            )

            h1_style = ParagraphStyle(
                'JarvisH1',
                parent=styles['Heading2'],
                fontSize=14,
                leading=18,
                textColor=colors.HexColor('#1F497D'),
                spaceBefore=12,
                spaceAfter=6
            )

            body_style = ParagraphStyle(
                'JarvisBody',
                parent=styles['Normal'],
                fontSize=10.5,
                leading=14,
                spaceAfter=8
            )

            story = [
                Paragraph(title, title_style),
                Paragraph("<i>Generated by JARVIS Autonomous Assistant</i>", styles['Italic']),
                Spacer(1, 20)
            ]

            for item in content:
                heading = item.get("heading", "")
                text = item.get("text", "") or item.get("content", "")
                if heading:
                    story.append(Paragraph(heading, h1_style))
                if text:
                    for para in text.split("\n\n"):
                        if para.strip():
                            story.append(Paragraph(para.replace("\n", "<br/>"), body_style))
                story.append(Spacer(1, 8))

            doc.build(story)
            logger.info(f"[Office] Created PDF document at {dest}")
            return f"PDF document successfully generated at: {dest}"

        except ImportError:
            dest_html = dest.with_suffix(".html")
            with open(dest_html, "w", encoding="utf-8") as f:
                f.write(f"<!DOCTYPE html><html><head><title>{title}</title><style>body{{font-family:Arial,sans-serif;margin:40px;line-height:1.6;color:#333;}}h1{{color:#1F497D;text-align:center;}}h2{{color:#1F497D;border-bottom:1px solid #ccc;}}</style></head><body>")
                f.write(f"<h1>{title}</h1><p style='text-align:center;color:#666;'><em>Generated by JARVIS</em></p><hr/>")
                for item in content:
                    f.write(f"<h2>{item.get('heading', '')}</h2>")
                    f.write(f"<p>{item.get('text', '').replace(chr(10), '<br>')}</p>")
                f.write("</body></html>")
            return f"PDF library not installed. Generated printable HTML at: {dest_html}"

    except Exception as e:
        logger.error(f"[Office PDF Error]: {e}")
        return f"Failed to generate PDF document: {e}"
