"""
JARVIS V4 - /v1/chat Route Module
Implements Section 11 & 12 of the V4 Specification:
POST /v1/chat -> ChatService -> Orchestrator -> AI Gateway -> Response.
"""

from __future__ import annotations

from typing import Optional, List, Dict, Any
from fastapi import APIRouter, Request, Header, HTTPException
from pydantic import BaseModel, Field

from orchestration.chat_service import get_chat_service, ChatRequestDTO

router = APIRouter(prefix="/v1", tags=["Chat V4"])


class V1ChatRequest(BaseModel):
    conversation_id: Optional[str] = None
    message: str = Field(..., max_length=4000)
    attachments: Optional[List[Dict[str, Any]]] = None
    confirmed: Optional[bool] = False


class V1ConfirmRequest(BaseModel):
    conversation_id: str
    tool_name: str
    arguments: Dict[str, Any] = Field(default_factory=dict)
    confirmed: bool = True


@router.post("/chat")
async def chat_v1_endpoint(payload: V1ChatRequest, request: Request, x_jarvis_token: Optional[str] = Header(None)):
    """
    Standard Authoritative V4 Chat API.
    Dispatches to ChatService and returns structured response.
    """
    from server import verify_auth
    verify_auth(request, x_jarvis_token)

    service = get_chat_service()
    dto = ChatRequestDTO(
        message=payload.message,
        conversation_id=payload.conversation_id,
        attachments=payload.attachments or [],
        confirmed=payload.confirmed or False,
        user_id="api_client"
    )
    resp = await service.handle(dto)
    return resp.to_dict()


@router.post("/chat/stream")
async def chat_stream_endpoint(payload: V1ChatRequest, request: Request, x_jarvis_token: Optional[str] = Header(None)):
    """
    Streaming Chat Endpoint (Server-Sent Events).
    Yields chunks as they are generated by the model/tool execution.
    """
    from server import verify_auth
    verify_auth(request, x_jarvis_token)

    import json
    from fastapi.responses import StreamingResponse

    service = get_chat_service()
    dto = ChatRequestDTO(
        message=payload.message,
        conversation_id=payload.conversation_id,
        attachments=payload.attachments or [],
        confirmed=payload.confirmed or False,
        user_id="desktop_client"
    )

    async def event_generator():
        async for chunk in service.handle_stream(dto):
            yield f"data: {json.dumps(chunk)}\n\n"

    return StreamingResponse(event_generator(), media_type="text/event-stream")



@router.post("/tools/{name}/confirm")
async def confirm_tool_endpoint(name: str, payload: V1ConfirmRequest, request: Request, x_jarvis_token: Optional[str] = Header(None)):
    """
    Approve or reject a pending sensitive action.
    """
    from server import verify_auth
    verify_auth(request, x_jarvis_token)

    service = get_chat_service()
    dto = ChatRequestDTO(
        message=f"Execute confirmed action: {name}",
        conversation_id=payload.conversation_id,
        confirmed=payload.confirmed,
        user_id="api_client"
    )
    resp = await service.handle(dto)
    return resp.to_dict()
